# Generated by Django 5.2.1 on 2025-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0004_scannedurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='scan_report_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
